version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
      - "9229:9229"  # VSCode 디버거 연결 (Vue.js)
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modules는 컨테이너 내부에서 유지
    command: ["npm", "run", "dev", "--", "--inspect=0.0.0.0:9229"]
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # 파일 변경 감지 (Mac & Docker 환경 최적화)

  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "5005:5005"  # Spring Boot 디버깅 포트
    volumes:
      - ./backend:/app
      # - /app/target      # Gradle/Maven 빌드 결과는 컨테이너 내부 유지
    command: ["./gradlew", "bootRun", "--continuous"]  # 개발 모드 실행
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVE_RELOAD_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/petpal_db
      - SPRING_DATASOURCE_USERNAME=petpal
      - SPRING_DATASOURCE_PASSWORD=petpal123
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: petpal
      POSTGRES_PASSWORD: petpal123
      POSTGRES_DB: petpal_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: